export const experienceList = [
  {
    id: 1,
    companyName: "Antino Labs",
    period: "Dec 2021 - Jun 2023 · 1 yr 7 mos",
    position: "React Developer",
    location: "Gurugram, Haryana, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/Antino.png",
  },
  {
    id: 2,
    companyName: "TREATMENT TRAVELLER ",
    period: "Apr 2020 - Dec 2021 · 1 yr 9 mos",
    position: "Frontend Web Developer",
    location: "Noida, Uttar Pradesh, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/ttLogo.png",
  },
  {
    id: 1,
    companyName: "Schneider Electric · Internship",
    period: "Oct 2019 - Nov 2019 · 2 mos",
    position: "Web Developer",
    location: "Chennai, Tamil Nadu, India",
    skills: ["JavaScript", "HTML", "Git", "REST API"],
    logo: "/schneider.jpeg",
  },
];
