export const experienceList = [
   {
    id: 1,
    companyName: "Zillit - India take one production",
    period: "nov 2023 - Nov 2024 · 1 Year",
    position: "Senior Web Developer",
    location: "Noida, Uttar Pradesh, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/schneider.jpeg",
  },
  {
    id: 2,
    companyName: "Antino Labs",
    period: "Jul 2022 - Jun 2023 · 1 yr",
    position: "React Developer",
    location: "Gurugram, Haryana, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/Antino.png",
  },
  {
    id: 3,
    companyName: "TREATMENT TRAVELLER ",
    period: "Dec 2020 - Jul 2022 · 1 yr 8 mos",
    position: "Frontend Web Developer",
    location: "Noida, Uttar Pradesh, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/ttLogo.png",
  },
  {
    id: 4,
    companyName: "Schneider Electric · Internship",
    period: "Oct 2019 - Nov 2019 · 2 mos",
    position: "Web Developer",
    location: "Chennai, Tamil Nadu, India",
    skills: ["JavaScript", "HTML", "Git", "REST API"],
    logo: "/schneider.jpeg",
  },
  
];
